### ISSUE TITLE
Why we trigger actions on `.github/workflows/**` ?

### ISSUE THREAD

**Issue by bigcat88** [nextcloud/.github#149]
In workflows phpunit-*.yml files

We should trigger them like this:
phpunit-mysql.yml: 
```
on:
  pull_request:
    paths:
        .github/workflows/phpunit-mysql.yml     <--- here trigger it only on self change
```

In phpunit-summary-when-unrelated.yml:
```
    paths-ignore:
      - '.github/workflows/phpunit-mysql.yml'
      - '.github/workflows/phpunit-oci.yml'
      - '.github/workflows/phpunit-pgsql.yml'
      - '.github/workflows/phpunit-sqlite.yml'
```

Can make a PR for this, if there is no objection to this
